### ISSUE TITLE
Prevent CDN caching images at `master` URLs

### ISSUE THREAD

**Issue by freeatnet** [arkon/uoft-enrolment-charts#5]
Steps to reproduce:
1. View a chart on https://echeung.me/uoft-enrolment-charts/# (eg., so that the page loads https://cdn.rawgit.com/arkon/uoft-enrolment-charts/master/charts/CSC/CSC358H1S.svg)
1. Update the chart
2. Attempt to view the updated chart via the website

Expected: new chart appears
Observed: new chart does not appear until the previous version expires off the CDN

**What can be done:**
We should use the latest SHA of `master` reference instead of directly referencing the branch name in the chart URL (eg., https://cdn.rawgit.com/arkon/uoft-enrolment-charts/dd195f3b3626f5b7a66aa200fabaa83fdb13813c/charts/CSC/CSC358H1S.svg).

We already fetch the repo tree [here](https://github.com/arkon/uoft-enrolment-charts/blob/master/site/src/assets/js/script.js#L63); since the call returns the latest SHA under `sha` key, we could just use it to form the appropriate chart URL.

**Comment by arkon** [comment]
Were you planning on implementing the change as well? If not, I can do it.
